[package]
name = "commands"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/commands.rs"
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
timeline = { version = "0.1.0", path = "../timeline" }
time = { version = "0.1.0", path = "../time" }
