"""DirectorLLM — LLM sebagai Sutradara Video.

Berbeda dari MandorLLM (yang hanya menganalisis brief),
DirectorLLM menghasilkan Edit Decision List (EDL) LENGKAP yang
langsung bisa dirender oleh FFmpeg menjadi video nyata.

Alur:
  user prompt → DirectorLLM → EDL JSON → EDLComposer → MP4

EDL (Edit Decision List) berisi:
  - Struktur scene lengkap
  - Query aset untuk Pexels/Pixabay
  - Script voiceover
  - Efek dan transisi
  - Color grading per scene
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)


# ── EDL Data Models ───────────────────────────────────────────────────────────

@dataclass
class EDLScene:
    """Single scene in the Edit Decision List."""
    id: int
    duration: float
    asset_query: str
    asset_type: str = "video"         # video | image | animation
    text_overlay: str = ""
    transition_in: str = "fade"
    transition_out: str = "crossfade"
    color_grade: str = "neutral"      # warm | cool | neutral | dramatic | none
    effects: list[str] = field(default_factory=list)
    voiceover_segment: str = ""
    asset_url: Optional[str] = None   # filled by AssetResolver
    asset_path: Optional[str] = None  # filled by AssetDownloader


@dataclass
class EditDecisionList:
    """Complete video blueprint generated by DirectorLLM."""
    title: str
    aspect_ratio: str = "16:9"
    fps: int = 30
    total_duration: float = 30.0
    voiceover_script: str = ""
    music_mood: str = "cinematic"
    scenes: list[EDLScene] = field(default_factory=list)

    # Metadata
    source_prompt: str = ""
    provider: str = "unknown"
    generation_time_ms: int = 0
    confidence: float = 0.8

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "aspect_ratio": self.aspect_ratio,
            "fps": self.fps,
            "total_duration": self.total_duration,
            "voiceover_script": self.voiceover_script,
            "music_mood": self.music_mood,
            "source_prompt": self.source_prompt,
            "provider": self.provider,
            "generation_time_ms": self.generation_time_ms,
            "confidence": self.confidence,
            "scenes": [
                {
                    "id": s.id,
                    "duration": s.duration,
                    "asset_query": s.asset_query,
                    "asset_type": s.asset_type,
                    "text_overlay": s.text_overlay,
                    "transition_in": s.transition_in,
                    "transition_out": s.transition_out,
                    "color_grade": s.color_grade,
                    "effects": s.effects,
                    "voiceover_segment": s.voiceover_segment,
                    "asset_url": s.asset_url,
                    "asset_path": s.asset_path,
                }
                for s in self.scenes
            ],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "EditDecisionList":
        scenes = [
            EDLScene(
                id=s["id"],
                duration=float(s.get("duration", 5)),
                asset_query=s.get("asset_query", "nature landscape"),
                asset_type=s.get("asset_type", "video"),
                text_overlay=s.get("text_overlay", ""),
                transition_in=s.get("transition_in", "fade"),
                transition_out=s.get("transition_out", "crossfade"),
                color_grade=s.get("color_grade", "neutral"),
                effects=s.get("effects", []),
                voiceover_segment=s.get("voiceover_segment", ""),
                asset_url=s.get("asset_url"),
                asset_path=s.get("asset_path"),
            )
            for s in data.get("scenes", [])
        ]
        return cls(
            title=data.get("title", "Untitled"),
            aspect_ratio=data.get("aspect_ratio", "16:9"),
            fps=int(data.get("fps", 30)),
            total_duration=float(data.get("total_duration", 30)),
            voiceover_script=data.get("voiceover_script", ""),
            music_mood=data.get("music_mood", "cinematic"),
            scenes=scenes,
            source_prompt=data.get("source_prompt", ""),
            provider=data.get("_provider", "unknown"),
            confidence=float(data.get("confidence", 0.8)),
        )


# ── Prompt Templates ──────────────────────────────────────────────────────────

def _build_edl_system_prompt(
    duration: int,
    style: str,
    platform: str,
    language: str,
    aspect_ratio: str,
) -> str:
    """Build the system prompt for EDL generation."""
    return f"""You are an award-winning video director and editor AI.
Your task is to create a complete Edit Decision List (EDL) for a video.

PARAMETERS:
- Duration: {duration} seconds total
- Style: {style}
- Platform: {platform} (aspect ratio: {aspect_ratio})
- Language: {language}
- Number of scenes: 3 to 6 (depending on duration)

RULES:
1. Return ONLY valid JSON — no markdown, no explanation, no code fences
2. Scene durations must sum to exactly {duration} seconds
3. asset_query must be in English (for Pexels/Pixabay search)
4. text_overlay and voiceover_script must be in {language}
5. Make asset queries specific and visual (e.g. "barista pouring latte art cafe morning")
6. Choose realistic durations: 4-12 seconds per scene
7. voiceover_script should be natural spoken language, not formal text

JSON SCHEMA (use exactly this structure):
{{
  "title": "Video title in {language}",
  "aspect_ratio": "{aspect_ratio}",
  "fps": 30,
  "total_duration": {duration},
  "voiceover_script": "complete narration for the whole video in {language}",
  "music_mood": "one of: cinematic, energetic, calm, fun, emotional, dramatic",
  "scenes": [
    {{
      "id": 1,
      "duration": 8.0,
      "asset_query": "specific visual search query in English",
      "asset_type": "video",
      "text_overlay": "short text to show (in {language}, max 5 words)",
      "transition_in": "fade",
      "transition_out": "crossfade",
      "color_grade": "warm",
      "effects": ["vignette"],
      "voiceover_segment": "narration for this scene in {language}"
    }}
  ]
}}

Valid transitions: fade, crossfade, wipe_left, wipe_right, zoom_in, dissolve, none
Valid color grades: warm, cool, neutral, dramatic, vintage, none
Valid effects: vignette, film_grain, blur_bg, zoom_slow, pan_left, pan_right, brightness_boost"""


def _fallback_edl(
    prompt: str,
    duration: int,
    style: str,
    platform: str,
    language: str,
) -> dict:
    """Hardcoded fallback EDL when all gateways are offline."""
    aspect_map = {
        "tiktok": "9:16", "reels": "9:16", "shorts": "9:16",
        "instagram": "1:1", "youtube": "16:9",
    }
    aspect_ratio = aspect_map.get(platform.lower(), "16:9")
    topic_words = prompt.split()[:4]
    topic = " ".join(topic_words)
    topic_en = topic  # used as-is for English search

    n_scenes = max(3, min(6, duration // 8))
    scene_dur = round(duration / n_scenes, 1)

    scenes = []
    scene_types = [
        (f"{topic_en} wide establishing shot", "Video pembuka", "warm", "fade", "crossfade"),
        (f"{topic_en} closeup detail", "", "neutral", "crossfade", "crossfade"),
        (f"{topic_en} action lifestyle", "Temukan lebih banyak", "cool", "crossfade", "fade"),
        (f"{topic_en} beauty product", "", "dramatic", "dissolve", "crossfade"),
        (f"{topic_en} people using", "Bergabung sekarang", "warm", "crossfade", "fade"),
        (f"{topic_en} sunset landscape", "OpenCut AI", "vintage", "fade", "fade"),
    ]

    for i in range(n_scenes):
        t = scene_types[i % len(scene_types)]
        scenes.append({
            "id": i + 1,
            "duration": scene_dur,
            "asset_query": t[0],
            "asset_type": "video",
            "text_overlay": t[1],
            "transition_in": t[3],
            "transition_out": t[4],
            "color_grade": t[2],
            "effects": ["vignette"] if i == 0 else [],
            "voiceover_segment": f"Scene {i+1}: {topic}",
        })

    return {
        "title": f"{topic.title()}",
        "aspect_ratio": aspect_ratio,
        "fps": 30,
        "total_duration": duration,
        "voiceover_script": f"Selamat menyaksikan video tentang {prompt}.",
        "music_mood": "cinematic",
        "_provider": "fallback",
        "scenes": scenes,
    }


# ── Main Class ────────────────────────────────────────────────────────────────

class DirectorLLM:
    """LLM-powered video director that generates complete EDLs.

    Cara kerja yang berbeda dari sistem AI video lainnya:
    - Tidak membutuhkan footage — AI mencari aset dari internet
    - Token cost = 0 (semua via free gateway)
    - LLM menghasilkan blueprint video yang langsung bisa dirender FFmpeg
    - User hanya perlu mengetik prompt, output berupa video MP4
    """

    def __init__(self):
        from moko_bridge.moko_client import MOKOClient
        self._client = MOKOClient()

    def generate_edl(
        self,
        prompt: str,
        duration: int = 30,
        style: str = "cinematic",
        platform: str = "youtube",
        language: str = "id",
    ) -> EditDecisionList:
        """Generate a complete Edit Decision List from a text prompt.

        Args:
            prompt: Natural language description of the video
            duration: Target duration in seconds
            style: Editing style (cinematic, vlog, tutorial, product, music)
            platform: Target platform (youtube, tiktok, instagram, reels, shorts)
            language: Language for text/script (id = Indonesian, en = English)

        Returns:
            EditDecisionList ready for EDLComposer to render
        """
        aspect_map = {
            "tiktok": "9:16", "reels": "9:16", "shorts": "9:16",
            "instagram": "1:1", "youtube": "16:9",
        }
        aspect_ratio = aspect_map.get(platform.lower(), "16:9")

        system = _build_edl_system_prompt(duration, style, platform, language, aspect_ratio)
        user_prompt = (
            f"Create a {duration}-second {style} video for {platform} about: {prompt}\n"
            f"Make it engaging, professional, and optimized for {platform}."
        )

        logger.info("[DirectorLLM] Generating EDL for: '%s' (%ds, %s, %s)", prompt, duration, style, platform)
        t_start = time.time()

        raw_edl = self._client.generate_edl(
            prompt=prompt,
            duration=duration,
            style=style,
            platform=platform,
            language=language,
        )

        elapsed_ms = int((time.time() - t_start) * 1000)

        if not raw_edl:
            logger.warning("[DirectorLLM] All gateways offline, using fallback EDL")
            raw_edl = _fallback_edl(prompt, duration, style, platform, language)

        edl = EditDecisionList.from_dict(raw_edl)
        edl.source_prompt = prompt
        edl.generation_time_ms = elapsed_ms

        # Validate & fix scene durations
        edl = self._validate_and_fix_edl(edl, duration)

        logger.info(
            "[DirectorLLM] EDL generated: %d scenes, %.1fs total, via %s (%dms)",
            len(edl.scenes), edl.total_duration, edl.provider, elapsed_ms,
        )
        return edl

    def generate_edl_with_retry(
        self,
        prompt: str,
        duration: int = 30,
        style: str = "cinematic",
        platform: str = "youtube",
        language: str = "id",
        max_retries: int = 2,
    ) -> EditDecisionList:
        """Generate EDL with retry on failure."""
        last_exc = None
        for attempt in range(max_retries + 1):
            try:
                return self.generate_edl(prompt, duration, style, platform, language)
            except Exception as e:
                last_exc = e
                logger.warning("[DirectorLLM] Attempt %d failed: %s", attempt + 1, e)
                if attempt < max_retries:
                    time.sleep(2 ** attempt)

        # Return fallback after all retries
        logger.error("[DirectorLLM] All retries failed: %s — returning fallback", last_exc)
        raw = _fallback_edl(prompt, duration, style, platform, language)
        return EditDecisionList.from_dict(raw)

    def refine_edl(
        self,
        edl: EditDecisionList,
        feedback: str,
    ) -> EditDecisionList:
        """Refine an existing EDL based on user feedback.

        Args:
            edl: The original EDL to refine
            feedback: User's feedback (e.g. "make it more energetic", "add more scenes")

        Returns:
            Refined EditDecisionList
        """
        system = (
            "You are a video editor. The user has feedback about their video plan. "
            "Modify the EDL JSON according to the feedback. "
            "Return ONLY valid JSON with the same schema, no explanation."
        )
        prompt = (
            f"Original EDL:\n{json.dumps(edl.to_dict(), indent=2)}\n\n"
            f"User feedback: {feedback}\n\n"
            "Return the modified EDL JSON."
        )

        result = self._client.llm_generate(
            prompt=prompt,
            system_prompt=system,
            max_tokens=2000,
            temperature=0.5,
        )

        if result and result.get("content"):
            raw = self._client._extract_json(result["content"])
            if raw:
                refined = EditDecisionList.from_dict(raw)
                refined.source_prompt = edl.source_prompt
                refined = self._validate_and_fix_edl(refined, int(edl.total_duration))
                return refined

        logger.warning("[DirectorLLM] Refine failed, returning original")
        return edl

    def _validate_and_fix_edl(self, edl: EditDecisionList, target_duration: int) -> EditDecisionList:
        """Validate EDL and fix common LLM output issues."""
        if not edl.scenes:
            logger.warning("[EDL] No scenes, adding default")
            edl.scenes = [EDLScene(
                id=1,
                duration=float(target_duration),
                asset_query=f"{edl.title} landscape",
                text_overlay=edl.title,
            )]

        # Fix scene durations to sum to target
        actual_total = sum(s.duration for s in edl.scenes)
        if abs(actual_total - target_duration) > 1.0:
            scale = target_duration / actual_total if actual_total > 0 else 1.0
            for scene in edl.scenes:
                scene.duration = round(scene.duration * scale, 1)
            edl.total_duration = target_duration

        # Validate scene IDs are sequential
        for i, scene in enumerate(edl.scenes):
            scene.id = i + 1

        # Validate aspect ratio
        valid_ratios = {"16:9", "9:16", "1:1", "4:3", "21:9"}
        if edl.aspect_ratio not in valid_ratios:
            edl.aspect_ratio = "16:9"

        # Validate fps
        if edl.fps not in (24, 25, 30, 60):
            edl.fps = 30

        # Validate transitions
        valid_transitions = {"fade", "crossfade", "wipe_left", "wipe_right",
                             "zoom_in", "dissolve", "none"}
        for scene in edl.scenes:
            if scene.transition_in not in valid_transitions:
                scene.transition_in = "fade"
            if scene.transition_out not in valid_transitions:
                scene.transition_out = "crossfade"

        # Distribute voiceover script to scenes
        if edl.voiceover_script and not any(s.voiceover_segment for s in edl.scenes):
            sentences = [s.strip() for s in edl.voiceover_script.split('.') if s.strip()]
            for i, scene in enumerate(edl.scenes):
                if i < len(sentences):
                    scene.voiceover_segment = sentences[i] + "."

        edl.total_duration = sum(s.duration for s in edl.scenes)
        return edl

    def get_gateway_status(self) -> dict:
        """Get status of all connected AI gateways."""
        return self._client.check_health()
