use serde::{Deserialize, Serialize};

#[cfg_attr(feature = "wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "wasm", tsify(from_wasm_abi, into_wasm_abi))]
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq)]
pub struct StickmanPose {
    pub body_y: f64,
    pub shoulder_l: f64,
    pub shoulder_r: f64,
    pub elbow_l: f64,
    pub elbow_r: f64,
    pub hip_l: f64,
    pub hip_r: f64,
    pub knee_l: f64,
    pub knee_r: f64,
    pub body_tilt: f64,
    pub pos_x: f64,
    pub pos_y: f64,

    pub neck: f64,
    pub head_turn: f64,
    pub clavicle_l: f64,
    pub clavicle_r: f64,
    pub wrist_l: f64,
    pub wrist_r: f64,
    pub ankle_l: f64,
    pub ankle_r: f64,
    pub spine_upper: f64,
    pub spine_lower: f64,
    pub pelvis: f64,
    pub finger_l: f64,
    pub finger_r: f64,
    pub toe_l: f64,
    pub toe_r: f64,

    pub eyebrow: f64,
    pub mouth: f64,
    pub eye_blink: f64,
    pub facing_left: bool,

    // Controls untuk kualitas film (Wajah, Dynamic Deformation, & Secondary Motion)
    pub squash_y: f64,
    pub stretch_x: f64,
    pub eye_squint: f64,
    pub pupil_x: f64,
    pub pupil_y: f64,
    pub brow_inner: f64,
    pub jaw_open: f64,
    pub secondary_hair_sway: f64,
    pub secondary_cloth_sway: f64,
    pub body_angle: f64,
    pub breath_offset: f64,
    pub finger_shape: f64,
    pub elbow_twist_l: f64,
    pub elbow_twist_r: f64,
    pub hip_twist_l: f64,
    pub hip_twist_r: f64,
    pub shoulder_scapular_l: f64,
    pub shoulder_scapular_r: f64,
    pub foot_roll_l: f64,
    pub foot_roll_r: f64,
    pub hand_rotation_l: f64,
    pub hand_rotation_r: f64,
    pub spine_neck: f64,
    pub breath_amplitude: f64,
    pub blink_timer: f64,
    pub brow_outer_l: f64,
    pub brow_outer_r: f64,
    pub cheek_puff: f64,
    pub nose_wrinkle: f64,
    pub lip_corner_l: f64,
    pub lip_corner_r: f64,
    pub lip_lower: f64,
    pub lip_upper: f64,
    pub tongue_out: f64,
}

impl StickmanPose {
    pub fn neutral() -> Self {
        let deg = |x: f64| x * std::f64::consts::PI / 180.0;
        Self {
            body_y: 0.0,
            shoulder_l: deg(-10.0),
            shoulder_r: deg(10.0),
            elbow_l: deg(5.0),
            elbow_r: deg(-5.0),
            hip_l: 0.0,
            hip_r: 0.0,
            knee_l: 0.0,
            knee_r: 0.0,
            body_tilt: 0.0,
            pos_x: 0.0,
            pos_y: 0.0,

            neck: 0.0,
            head_turn: 0.0,
            clavicle_l: 0.0,
            clavicle_r: 0.0,
            wrist_l: 0.0,
            wrist_r: 0.0,
            ankle_l: 0.0,
            ankle_r: 0.0,
            spine_upper: 0.0,
            spine_lower: 0.0,
            pelvis: 0.0,
            finger_l: 0.0,
            finger_r: 0.0,
            toe_l: 0.0,
            toe_r: 0.0,

            eyebrow: 0.0,
            mouth: 0.0,
            eye_blink: 0.0,
            facing_left: false,

            squash_y: 1.0,
            stretch_x: 1.0,
            eye_squint: 0.0,
            pupil_x: 0.0,
            pupil_y: 0.0,
            brow_inner: 0.0,
            jaw_open: 0.0,
            secondary_hair_sway: 0.0,
            secondary_cloth_sway: 0.0,
            body_angle: 0.0,
            breath_offset: 0.0,
            finger_shape: 0.0,
            elbow_twist_l: 0.0,
            elbow_twist_r: 0.0,
            hip_twist_l: 0.0,
            hip_twist_r: 0.0,
            shoulder_scapular_l: 0.0,
            shoulder_scapular_r: 0.0,
            foot_roll_l: 0.0,
            foot_roll_r: 0.0,
            hand_rotation_l: 0.0,
            hand_rotation_r: 0.0,
            spine_neck: 0.0,
            breath_amplitude: 0.0,
            blink_timer: 0.0,
            brow_outer_l: 0.0,
            brow_outer_r: 0.0,
            cheek_puff: 0.0,
            nose_wrinkle: 0.0,
            lip_corner_l: 0.0,
            lip_corner_r: 0.0,
            lip_lower: 0.0,
            lip_upper: 0.0,
            tongue_out: 0.0,
        }
    }

    pub fn lerp(a: &Self, b: &Self, t: f64) -> Self {
        let lerp = |x: f64, y: f64| x + (y - x) * t;
        Self {
            body_y: lerp(a.body_y, b.body_y),
            shoulder_l: lerp(a.shoulder_l, b.shoulder_l),
            shoulder_r: lerp(a.shoulder_r, b.shoulder_r),
            elbow_l: lerp(a.elbow_l, b.elbow_l),
            elbow_r: lerp(a.elbow_r, b.elbow_r),
            hip_l: lerp(a.hip_l, b.hip_l),
            hip_r: lerp(a.hip_r, b.hip_r),
            knee_l: lerp(a.knee_l, b.knee_l),
            knee_r: lerp(a.knee_r, b.knee_r),
            body_tilt: lerp(a.body_tilt, b.body_tilt),
            pos_x: lerp(a.pos_x, b.pos_x),
            pos_y: lerp(a.pos_y, b.pos_y),

            neck: lerp(a.neck, b.neck),
            head_turn: lerp(a.head_turn, b.head_turn),
            clavicle_l: lerp(a.clavicle_l, b.clavicle_l),
            clavicle_r: lerp(a.clavicle_r, b.clavicle_r),
            wrist_l: lerp(a.wrist_l, b.wrist_l),
            wrist_r: lerp(a.wrist_r, b.wrist_r),
            ankle_l: lerp(a.ankle_l, b.ankle_l),
            ankle_r: lerp(a.ankle_r, b.ankle_r),
            spine_upper: lerp(a.spine_upper, b.spine_upper),
            spine_lower: lerp(a.spine_lower, b.spine_lower),
            pelvis: lerp(a.pelvis, b.pelvis),
            finger_l: lerp(a.finger_l, b.finger_l),
            finger_r: lerp(a.finger_r, b.finger_r),
            toe_l: lerp(a.toe_l, b.toe_l),
            toe_r: lerp(a.toe_r, b.toe_r),

            eyebrow: lerp(a.eyebrow, b.eyebrow),
            mouth: lerp(a.mouth, b.mouth),
            eye_blink: lerp(a.eye_blink, b.eye_blink),
            facing_left: a.facing_left,

            squash_y: lerp(a.squash_y, b.squash_y),
            stretch_x: lerp(a.stretch_x, b.stretch_x),
            eye_squint: lerp(a.eye_squint, b.eye_squint),
            pupil_x: lerp(a.pupil_x, b.pupil_x),
            pupil_y: lerp(a.pupil_y, b.pupil_y),
            brow_inner: lerp(a.brow_inner, b.brow_inner),
            jaw_open: lerp(a.jaw_open, b.jaw_open),
            secondary_hair_sway: lerp(a.secondary_hair_sway, b.secondary_hair_sway),
            secondary_cloth_sway: lerp(a.secondary_cloth_sway, b.secondary_cloth_sway),
            body_angle: lerp(a.body_angle, b.body_angle),
            breath_offset: lerp(a.breath_offset, b.breath_offset),
            finger_shape: lerp(a.finger_shape, b.finger_shape),
            elbow_twist_l: lerp(a.elbow_twist_l, b.elbow_twist_l),
            elbow_twist_r: lerp(a.elbow_twist_r, b.elbow_twist_r),
            hip_twist_l: lerp(a.hip_twist_l, b.hip_twist_l),
            hip_twist_r: lerp(a.hip_twist_r, b.hip_twist_r),
            shoulder_scapular_l: lerp(a.shoulder_scapular_l, b.shoulder_scapular_l),
            shoulder_scapular_r: lerp(a.shoulder_scapular_r, b.shoulder_scapular_r),
            foot_roll_l: lerp(a.foot_roll_l, b.foot_roll_l),
            foot_roll_r: lerp(a.foot_roll_r, b.foot_roll_r),
            hand_rotation_l: lerp(a.hand_rotation_l, b.hand_rotation_l),
            hand_rotation_r: lerp(a.hand_rotation_r, b.hand_rotation_r),
            spine_neck: lerp(a.spine_neck, b.spine_neck),
            breath_amplitude: lerp(a.breath_amplitude, b.breath_amplitude),
            blink_timer: lerp(a.blink_timer, b.blink_timer),
            brow_outer_l: lerp(a.brow_outer_l, b.brow_outer_l),
            brow_outer_r: lerp(a.brow_outer_r, b.brow_outer_r),
            cheek_puff: lerp(a.cheek_puff, b.cheek_puff),
            nose_wrinkle: lerp(a.nose_wrinkle, b.nose_wrinkle),
            lip_corner_l: lerp(a.lip_corner_l, b.lip_corner_l),
            lip_corner_r: lerp(a.lip_corner_r, b.lip_corner_r),
            lip_lower: lerp(a.lip_lower, b.lip_lower),
            lip_upper: lerp(a.lip_upper, b.lip_upper),
            tongue_out: lerp(a.tongue_out, b.tongue_out),
        }
    }
}

impl Default for StickmanPose {
    fn default() -> Self {
        Self::neutral()
    }
}
